### ISSUE TITLE
Add some basic html functional tests

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website-build-prod#1]
Use the Symfony crawler to click through the html of the site and look for broken links.

**Comment by Ocramius** [comment]
Much much much much simpler: http://www.lostsaloon.com/technology/how-to-use-wget-to-find-broken-links-on-your-website/

**Comment by jwage** [comment]
I want to do a little more than just look for 404s and I don't want to rely on it being deployed on a web server. I plan on setting up something that lets me get the homepage, click a project, click docs, etc and assert things on the html.

**Comment by jwage** [comment]
Just realized I added this to the wrong repo
