### ISSUE TITLE
Document "magic finder" calls in more comprehensive and referenceable way

### ISSUE THREAD

**Issue by olberger** [doctrine/doctrine-website-build-prod#2]
I think the findBy* "magic" finder methods would deserve a better and more explicit documentation, which would also deserve a referenceable anchor (for pointing to it from other docs, like Symfony's, etc.).

The docs mention that "An EntityRepository also provides a mechanism for more concise calls through its use of __call" (later the code mentions the "__call magic"), in
https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#entities-and-the-identity-map

AFAIU, this is here:
https://github.com/doctrine/doctrine-website-build-prod/blob/bdf72516f727f3efa70c6db187eb7e8601ef2e9e/projects/doctrine-orm/en/latest/reference/working-with-objects.html#L1004

The mechanism isn't really documented, and is just an example.

https://www.doctrine-project.org/api/orm/2.7/Doctrine/ORM/EntityRepository.html#method___call is rather sybylline ins this respect too: "Adds support for magic method calls."

Thanks in advance.

**Comment by Ocramius** [comment]
I'd rather say that their usage should be discouraged: an associative array will provide better introspection here.

Anyway, sources for the docs of the ORM are in https://github.com/doctrine/doctrine2 - closing here.

**Comment by olberger** [comment]
My bad... it's not obvious from the outside what this repo is about... may I suggest to improve its description in its github landing page ?

**Comment by Ocramius** [comment]
Good call, shall do 👍
